WORD_TYPES = {

	#Directions
	
    "north" : "direction",
    "south" : "direction", 
    "east" : "direction",
    "west" : "direction",
	"down" : "direction", 
	"up" : "direction", 
	"left" : "direction", 
	"right" : "direction", 
	"back" : "direction",
	"forward" : "direction",	
	
	
	#Verbs
	"move" : "verb",	
    "go" : "verb",
    "eat" : "verb",
	"stop": "verb", 
	"eat" : "verb", 
	"look" : "verb", 
	"at": "verb", 
	"take": "verb", 
	"help": "verb", 
	"inventory": "verb",
	"savegame": "verb", 
	"loadgame": "verb", 
	"talk": "verb", 
	"ask": "verb", 
	"open": "verb", 
	"close": "verb", 
	"sleep": "verb", 
	"sneak": "verb",
	"walk": "verb", 
	"run": "verb", 
	"drop": "verb", 
	"use": "verb", 
	"push": "verb", 
	"pull": "verb", 
	"eat": "verb", 
	"drink": "verb",
	"grab": "verb", 
	"pick up":"verb", 
	
	
	#Stop words
	
	"a" : "stop", 
	"about" : "stop", 
	"above" : "stop", 
	"after" : "stop", 
	"again" : "stop", 
	"against" : "stop", 
	"all" : "stop", 
	"am" : "stop", 
	"an" : "stop", 
	"and" : "stop", 
	"any" : "stop", 
	"are" : "stop", 
	"as" : "stop", 
	"at" : "stop",
	"be" : "stop", 
	"because" : "stop", 
	"been" : "stop", 
	"before" : "stop", 
	"being" : "stop", 
	"below" : "stop", 
	"between" : "stop", 
	"both" : "stop", 
	"but" : "stop", 
	"by" : "stop", 
	"can" : "stop", 
	"did" : "stop", 
	"do" : "stop", 
	"does" : "stop", 
	"doing" : "stop", 
	"don't" : "stop", 
	"down" : "stop", 
	"during" : "stop", 
	"each" : "stop", 
	"few" : "stop", 
	"for" : "stop", 
	"from" : "stop", 
	"further" : "stop", 
	"had" : "stop", 
	"has" : "stop", 
	"have" : "stop", 
	"having" : "stop", 
	"he" : "stop", 
	"her" : "stop", 
	"here" : "stop", 
	"hers" : "stop", 
	"herself" : "stop", 
	"him" : "stop", 
	"himself" : "stop", 
	"his" : "stop", 
	"how" : "stop", 
	"I" : "stop", 
	"if" : "stop",
	"in" : "stop",
	"into" : "stop", 
	"is" : "stop", 
	"it" : "stop", 
	"its" : "stop", 
	"itself" : "stop", 
	"just" : "stop", 
	"me" : "stop", 
	"more" : "stop", 
	"most" : "stop", 
	"my" : "stop", 
	"myself" : "stop", 
	"no" : "stop", 
	"nor" : "stop", 
	"not" : "stop", 
	"now" : "stop", 
	"of" : "stop", 
	"off" : "stop", 
	"on" : "stop", 
	"once" : "stop", 
	"only" : "stop", 
	"onto" : "stop", 
	"or" : "stop", 
	"other" : "stop", 
	"our" : "stop", 
	"ours" : "stop", 
	"ourselves" : "stop", 
	"out" : "stop", 
	"over" : "stop", 
	"own" : "stop", 
	"quick" : "stop",
	"quickly" : "stop", 
	"s" : "stop", 
	"same" : "stop", 
	"she" : "stop", 
	"should" : "stop",
	"so" : "stop", 
	"some" : "stop", 
	"such" : "stop", 
	"t" : "stop", 
	"than" : "stop", 
	"that" : "stop", 
	"the" : "stop", 
	"their" : "stop", 
	"theirs" : "stop", 
	"them" : "stop", 
	"themselves" : "stop", 
	"then" : "stop", 
	"there" : "stop", 
	"these" : "stop", 
	"they" : "stop", 
	"this" : "stop",
	"those" : "stop", 
	"through" : "stop", 
	"to" : "stop", 
	"too" : "stop", 
	"under" : "stop", 
	"until" : "stop", 
	"up" : "stop", 
	"very" : "stop", 
	"was" : "stop", 
	"we" : "stop", 
	"were" : "stop", 
	"what" : "stop", 
	"when" : "stop",
	"where" : "stop", 
	"which" : "stop", 
	"while" : "stop", 
	"who" : "stop", 
	"whom" : "stop", 
	"why" : "stop", 
	"will" : "stop", 
	"with" : "stop", 
	"you" : "stop", 
	"your" : "stop", 
	"yours" : "stop", 
	"yourself" : "stop", 
	"yourselves" : "stop", 

	
	#Nouns
	
    "door" : "noun", 
	"backpack" : "noun", 
	"bookbag" : "noun", 
	"desk" : "noun", 
	"dry erase marker" : "noun", 
	"gym bag" : "noun", 
	"chair" : "noun", 
	"white board" : "noun", 
	"book" : "noun", 
	"ruler" : "noun", 
	"yardstick" : "noun", 
	"beaker" : "noun", 
	"bunsen burner" : "noun", 
	"chemicals" : "noun", 
	"chalk" : "noun", 
	"highlighters" : "noun", 
	"phone" : "noun", 
	"headphones" : "noun", 
	"camera" : "noun", 
	"magnifying glass" : "noun", 
	"tablet" : "noun", 
	"laptop" : "noun", 
	"computer" : "noun", 
	"locker" : "noun", 
	"cloths" : "noun", 
	"calcculator" : "noun", 
	"water" : "noun", 
	"water fountain" : "noun", 
	"food trays" : "noun", 
	"tables" : "noun", 
	"fire alarm" : "noun",
	"hall monitor" : "noun", 
	"dodge ball team" : "noun", 
	"coach" : "noun", 
	"librarian" : "noun", 
	"vice principal" : "noun", 
	"principal" : "noun", 
	"janitor" : "noun", 
	"custodian" : "noun", 
	"cafeteria cook" : "noun", 
	"cook" : "noun", 
	"counselor" : "noun", 
	"computer teacher" : "noun", 
	"teacher" : "noun", 
	"chemistry teacher" : "noun", 
	"matches" : "noun", 
	"lighter" : "noun", 
	"web pages" : "noun", 
	"e-mail" : "noun",
	"email" : "noun", 
	"calculator" : "noun", 
	"batteries" : "noun", 
	"water" : "noun",

	#Rooms
	"bathroom" : "noun",
	"cafeteria" : "noun",
	"chemistry" : "noun",
	"computer" : "noun",
	"counselor" : "noun",
	"detention" : "noun",
	"gym" : "noun",
	"hallway1" : "noun",
	"hallway2" : "noun",
	"hallway3" : "noun",
	"janitor" : "noun",
	"library" : "noun",
	"main" : "noun",
	"math" : "noun",
	"music" : "noun",
	"principal" : "noun",
	"supply" : "noun"


}

def convert_number(word):
    try:
        return int(word)
    except:
        return None

def scan(sentence):
    words = sentence.split()
    results = []

    for word in words:
        word_type = WORD_TYPES.get(word)
        
        if word_type == None:
            # it might be a number, so try converting
            number = convert_number(word)

            if number != None:
                results.append(("number", number))
            else:
                results.append(("error", word))
        else:
            results.append((word_type, word))
   
    return results
